apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "82098203-ingress"
spec:
  ingressClassName: ingress-internal
  rules:
  - host: app-82098203.ce-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: app-82098203
            port:
              number: 8080
        pathType: Prefix
